### ISSUE TITLE
Upload files bigger than 1MB? do not work

### ISSUE THREAD

**Issue by jvicens** [NoOPeEKS/decidim-tutorial#6]
In theory, I should be able to upload files/images until 10MB, however, when I try it the application does not upload the content. Only works with small files. 

Ping me to reproduce the "error"

**Comment by NoOPeEKS** [comment]
Hi @jvicens, this is probably related to NGINX's default limit file upload size being 1MB. Add the following line "client_max_body_size 10M;" under the proxy_passes in nginx.conf file. [Here is the reference](https://docs.rackspace.com/docs/limit-file-upload-size-in-nginx). If this doesn't work, then it's surely Decidim's environment variable called `DECIDIM_MAXIMUM_ATTACHMENT_SIZE`. Its default should be 10MB, but try to assign it to 10 or more in `docker-compose.yml`. [Decidim Environment Variables reference](https://docs.decidim.org/en/develop/configure/environment_variables)
