### ISSUE TITLE
Pictures loaded in the platform with link corrupted after a while

### ISSUE THREAD

**Issue by jvicens** [NoOPeEKS/decidim-tutorial#7]
Some of the links to the images are corrupted. It happens with all the pictures in the blog post and the main image in the home.
For reproducibility, you should delete the cache.

Here some examples where a picture should appear:

https://decidim.eurecatprojects.com/
<img width="1274" alt="Screenshot 2024-05-30 at 07 51 07" src="https://github.com/NoOPeEKS/decidim-deployment-guide/assets/5405396/a13fef8b-70bf-40e7-9740-c84aa39ec7bf">

and here where the avatar and main image of the blog post do not appear:

https://decidim.eurecatprojects.com/processes/cstoolkit/f/8/posts/1
<img width="1274" alt="Screenshot 2024-05-30 at 07 52 18" src="https://github.com/NoOPeEKS/decidim-deployment-guide/assets/5405396/b65782ef-be59-4723-977e-35f5c2366e96">

**Comment by jvicens** [comment]
Here you have the error in the console about the image of the main page:

<img width="417" alt="Screenshot 2024-05-30 at 13 53 23" src="https://github.com/NoOPeEKS/decidim-deployment-guide/assets/5405396/a7e9c6e9-da68-49ac-b2d6-23255a85aa6d">

**Comment by NoOPeEKS** [comment]
Hi @jvicens, this error was found to be that we did not add a volume in the `docker-compose.yml` file and whenever the server would be restarted, all data found in local storage would be resetted. Having a persistent volume fixes that issue between server resets. I'm closing this issue now, thank you for warning us!
